matrix:
  include:
    - language: scala
      jdk: oraclejdk8
      scala: 
        - 2.12.8
      before_script:
        - cd server
      script: 
        - sbt test
        
    - language: node_js
      node_js:
        - "8"
      cache: yarn
      before_script:
        - cd reason-frontend
      script: ["yarn add coveralls", "yarn bsb -clean-world -make-world", "yarn coverage"]
