# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  "server":
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk-node

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m -Xss4m
      TERM: dumb

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "server/build.sbt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: cd server; cat /dev/null | sbt test:compile

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies--{{ checksum "server/build.sbt" }}

    # run tests!
    - run: cd server; cat /dev/null | sbt clean validate
    - run: cd server; bash <(curl -s https://codecov.io/bash)
  "frontend":
    docker:
      - image: circleci/node:9
    
    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - vnode-v1-{{ .Branch }}-{{ checksum "reason-frontend/yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - node-v1-{{ .Branch }}-

    - run: cd reason-frontend; yarn

    - save_cache:
        paths:
        - ~/usr/local/lib/node_modules
        key: node-v1-{{ .Branch }}-{{ checksum "reason-frontend/yarn.lock" }}

    # - run: cd reason-frontend; yarn add coveralls
    - run: cd reason-frontend; yarn bsb -clean-world -make-world
    - run: cd reason-frontend; yarn coverage
workflows:
  version: 2
  build:
    jobs:
      - "server"
      - "frontend"
